---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awx-restore
  namespace: awx
spec:
  no_log: false
  deployment_name: awx-restore
  backup_name: "{{ target_backup }}"
  backup_pvc_namespace: awx
  postgres_configuration_secret: awx-postgres-configuration

