AWX_GITHUB_USERNAME: "{{ awx_credentials.json.data.data.AWX_GITHUB_USERNAME }}"
AWX_GITHUB_PAT: "{{ awx_credentials.json.data.data.AWX_GITHUB_PAT }}"
AWX_SSH_KEY_PRIV_BASE64: "{{ awx_credentials.json.data.data.AWX_SSH_KEY_PRIV_BASE64 | b64decode }}"
KUBESPRAY_ED25519: "{{ awx_credentials.json.data.data.KUBESPRAY_ED25519 | b64decode }}"
ARTIFACTORY_PASSWORD: "{{ awx_credentials.json.data.data.ARTIFACTORY_PASSWORD }}"
vault_url: https://vault-kuber-dev.np-store-monarch.str.homedepot.coml
