---
- name: awx-backup
  hosts: all
  gather_facts: false
  become: true
  collections:
  - kubernetes.core
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
    artifactory_username: "{{ lookup('env', 'ARTIFACTORY_USERNAME') }}"
    artifactory_password: "{{ lookup('env', 'ARTIFACTORY_PASSWORD') }}"
  roles:
  - awx-backup
